### PR TITLE
deply to https://auto20-next.pages.dev/#/profile 和 https://we.alearn.org.tw/#/ 但是sh deploy.sh 有error: failed to push some refs to 'github.com:3dw/auto20-next.git'

### PR DESCRIPTION
**Pull request by leechiuhui**

### CODE REVIEW

**Comment by bestian** [comment]
試試看先設定
ssh-key

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by leechiuhui** [comment]
Thank you, teacher, for your kind reply. I will try it on next Tuesday.

**Comment by leechiuhui** [comment]
> 試試看先設定 ssh-key ssh-金鑰
> https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Teacher, I have set the SSH key on my personal GitHub account as shown in the image below, but it seems that I still cannot deploy to https://we.alearn.org.tw/.
截圖 2024-06-25 上午10 30 49

Also, I don't think I should add the SSH key to the 3dw organization's GitHub account as shown in the two images below, right?
截圖 2024-06-25 上午10 59 57
截圖 2024-06-25 上午11 00 13

Therefore, teacher, could my problem be that I don't have permissions for Cloudflare.com, as shown in the last image below?截圖 2024-06-25 上午11 06 11

**Comment by bestian** [comment]
這和cloudFlare那邊沒關係
deploy.sh的內容只是把它build出來後, 前往dist資料夾, 把內容push上gh-pages這個branch.

我可能需要看一下命令列上在跑 sh deploy.sh時的完整資訊和錯誤碼, 才能知道如何debug

**Comment by bestian** [comment]
Indeed, 我看到gh-pages有成功更新, 代表we.alearn.org.tw有成功更新
check status 3/4的錯誤是可以忽略的, 因為那是cloudFlare auto-deploy自己生成的, 可以不管它.

**Comment by leechiuhui** [comment]
> Indeed, 我剛剛注意到gh-pages有成功更新, 代表we.alearn.org.tw有成功更新 check status 3/4的錯誤是可以忽略的, 因為那是cloudFlare auto-deploy自己生成的, 可以不管它.

對，這幾次(算是一直以來）我觀察gh-pages都有成功更新，但是我測https://we.alearn.org.tw的運作還是沒有最新程式碼的作用...
take your time..teacher

**Comment by leechiuhui** [comment]
> 這和cloudFlare那邊沒關係 deploy.sh的內容只是把它build出來後, 前往dist資料夾, 把內容push上gh-pages這個branch.
> 
> 我可能需要看一下命令列上在跑 sh deploy.sh時的完整資訊和錯誤碼, 才能知道如何debug?


(base) chiuhuilee@ChiudeMacBook-Pro 3dw-auto20-next-20240621 % sh deploy.sh
yarn run v1.22.19
$ vue-cli-service build
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠧  Building for production...

 WARNING  Compiled with 4 warnings                                                     下午12:36:08

[eslint] 
/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/App.vue
  125:25  warning  'placesRef' is defined but never used  @typescript-eslint/no-unused-vars
  196:5   warning  Unexpected console statement           no-console
  210:7   warning  Unexpected console statement           no-console
  222:7   warning  Unexpected console statement           no-console
  223:7   warning  Unexpected console statement           no-console
  228:7   warning  Unexpected console statement           no-console
  234:9   warning  Unexpected console statement           no-console
  237:11  warning  Unexpected console statement           no-console
  266:7   warning  Unexpected console statement           no-console
  269:9   warning  Unexpected console statement           no-console
  276:7   warning  Unexpected console statement           no-console
  282:13  warning  Unexpected console statement           no-console
  285:15  warning  Unexpected console statement           no-console
  289:13  warning  Unexpected console statement           no-console
  293:9   warning  Unexpected console statement           no-console
  297:7   warning  Unexpected console statement           no-console
  301:7   warning  Unexpected console statement           no-console
  327:7   warning  Unexpected console statement           no-console
  334:11  warning  Unexpected console statement           no-console
  345:9   warning  Unexpected console statement           no-console
  361:11  warning  Unexpected console statement           no-console
  375:11  warning  Unexpected console statement           no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/components/Card.vue
  186:7   warning  Unexpected console statement  no-console
  190:7   warning  Unexpected console statement  no-console
  194:7   warning  Unexpected console statement  no-console
  214:11  warning  Unexpected console statement  no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/components/Chatbox.vue
  147:11  warning  Unexpected console statement  no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/components/HelloWorld.vue
  153:7  warning  Unexpected console statement  no-console
  157:7  warning  Unexpected console statement  no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/views/BookView.vue
  147:7  warning  Unexpected console statement  no-console
  151:7  warning  Unexpected console statement  no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/views/FlagView.vue
  70:7  warning  Unexpected console statement  no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/views/FriendsView.vue
   73:15  warning  'today' is assigned a value but never used  @typescript-eslint/no-unused-vars
   94:5   warning  Unexpected console statement                no-console
   95:5   warning  Unexpected console statement                no-console
  101:7   warning  Unexpected console statement                no-console
  109:7   warning  Unexpected console statement                no-console
  119:9   warning  Unexpected console statement                no-console
  207:9   warning  Unexpected console statement                no-console
  213:9   warning  Unexpected console statement                no-console
  250:7   warning  Unexpected console statement                no-console
  254:7   warning  Unexpected console statement                no-console
  264:13  warning  Unexpected console statement                no-console
  268:13  warning  Unexpected console statement                no-console
  272:9   warning  Unexpected console statement                no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/views/GroupView.vue
  151:9   warning  Unexpected console statement  no-console
  161:9   warning  Unexpected console statement  no-console
  189:9   warning  Unexpected console statement  no-console
  203:9   warning  Unexpected console statement  no-console
  214:9   warning  Unexpected console statement  no-console
  224:17  warning  Unexpected console statement  no-console
  227:11  warning  Unexpected console statement  no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/views/GroupsView.vue
  101:9   warning  Unexpected console statement  no-console
  112:11  warning  Unexpected console statement  no-console
  141:9   warning  Unexpected console statement  no-console
  155:9   warning  Unexpected console statement  no-console
  166:9   warning  Unexpected console statement  no-console
  175:9   warning  Unexpected console statement  no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/views/HomeView.vue
  61:7  warning  Unexpected console statement  no-console
  65:7  warning  Unexpected console statement  no-console

/Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/src/views/ProfileView.vue
  307:11  warning  Unexpected console statement  no-console
  321:9   warning  Unexpected console statement  no-console
  412:9   warning  Unexpected console statement  no-console
  446:7   warning  Unexpected console statement  no-console

✖ 64 problems (0 errors, 64 warnings)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 warning  

/js/chunk-vendors.081b6c90.js.map is 3.01 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  img/icons.a93cf03c.svg (382 KiB)
  img/brand-icons.b0ccb869.svg (496 KiB)
  img/handshake1.c81ff127.webp (316 KiB)
  css/chunk-vendors.d680ee65.css (532 KiB)
  js/chunk-vendors.081b6c90.js (574 KiB)
  logo-new-1.png (896 KiB)
  img/icons-ver1/android-chrome-512x512.png (498 KiB)
  img/icons-ver1/android-chrome-maskable-512x512.png (498 KiB)
  img/icons-原來在img:下/android-chrome-512x512.png (498 KiB)
  img/icons-原來在img:下/android-chrome-maskable-512x512.png (498 KiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.15 MiB)
      css/chunk-vendors.d680ee65.css
      js/chunk-vendors.081b6c90.js
      css/app.8dcb552f.css
      js/app.abbabb22.js


  File                                    Size                       Gzipped

  dist/js/chunk-vendors.081b6c90.js       573.60 KiB                 147.63 KiB
  dist/js/886.54748357.js                 150.48 KiB                 43.98 KiB
  dist/js/app.abbabb22.js                 66.65 KiB                  23.83 KiB
  dist/js/maps.09bfd3ba.js                37.12 KiB                  10.10 KiB
  dist/js/qr.9744bb99.js                  31.62 KiB                  11.88 KiB
  dist/js/profile.521b4f0e.js             18.64 KiB                  4.93 KiB
  dist/workbox-6567b62a.js                14.11 KiB                  4.91 KiB
  dist/js/groups.033810f8.js              13.71 KiB                  3.38 KiB
  dist/js/about.85cad187.js               13.63 KiB                  3.96 KiB
  dist/service-worker.js                  9.85 KiB                   2.43 KiB
  dist/js/privacy-policy.5dc0b6de.js      2.88 KiB                   1.04 KiB
  dist/js/book.6ef90e1f.js                2.66 KiB                   1.37 KiB
  dist/js/flag.ec454913.js                1.58 KiB                   0.86 KiB
  dist/css/chunk-vendors.d680ee65.css     532.47 KiB                 96.67 KiB
  dist/css/maps.5fa7a45c.css              16.34 KiB                  6.61 KiB
  dist/css/profile.02c070f7.css           14.90 KiB                  6.32 KiB
  dist/css/app.8dcb552f.css               4.04 KiB                   1.39 KiB
  dist/css/book.8da445d2.css              0.66 KiB                   0.26 KiB
  dist/css/privacy-policy.7f4fe48c.css    0.63 KiB                   0.30 KiB
  dist/css/groups.6b6b3054.css            0.41 KiB                   0.17 KiB
  dist/css/about.5c4dff17.css             0.18 KiB                   0.14 KiB
  dist/css/flag.4e5993e3.css              0.16 KiB                   0.14 KiB
  dist/css/qr.b7c52485.css                0.04 KiB                   0.06 KiB

  Images and other types of assets omitted.
  Build at: 2024-06-25T04:36:08.215Z - Hash: f5fb278b4ead80dd - Time: 6054ms

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
       
✨  Done in 7.07s.
Initialized empty Git repository in /Users/chiuhuilee/Documents/GitHub/3dw-auto20-next-20240621/dist/.git/
[main (root-commit) 8c89ffc] deploy
 129 files changed, 6588 insertions(+)
 create mode 100644 CNAME
 create mode 100644 css/about.5c4dff17.css
 create mode 100644 css/app.8dcb552f.css
 create mode 100644 css/book.8da445d2.css
 create mode 100644 css/chunk-vendors.d680ee65.css
 create mode 100644 css/flag.4e5993e3.css
 create mode 100644 css/groups.6b6b3054.css
 create mode 100644 css/maps.5fa7a45c.css
 create mode 100644 css/privacy-policy.7f4fe48c.css
 create mode 100644 css/profile.02c070f7.css
 create mode 100644 css/qr.b7c52485.css
 create mode 100644 favicon-1.ico
 create mode 100644 favicon.ico
 create mode 100644 fonts/brand-icons.1a368124.ttf
 create mode 100644 fonts/brand-icons.a5c2b578.eot
 create mode 100644 fonts/brand-icons.d3632e64.woff2
 create mode 100644 fonts/brand-icons.ff793786.woff
 create mode 100644 fonts/icons.004393de.woff
 create mode 100644 fonts/icons.62a2bfb1.woff2
 create mode 100644 fonts/icons.8ec0357f.ttf
 create mode 100644 fonts/icons.fa5c061f.eot
 create mode 100644 fonts/outline-icons.315b68a4.woff
 create mode 100644 fonts/outline-icons.3c7c2806.eot
 create mode 100644 fonts/outline-icons.ba204dab.ttf
 create mode 100644 fonts/outline-icons.d24ca609.woff2
 create mode 100644 img/Cc_by-nd_icon.svg.3bcd59c2.png
 create mode 100644 img/android-chrome-192x192.png
 create mode 100644 img/android-chrome-512x512.png
 create mode 100644 img/android-chrome-maskable-192x192.png
 create mode 100644 img/android-chrome-maskable-512x512.png
 create mode 100644 img/apple-touch-icon-120x120.png
 create mode 100644 img/apple-touch-icon-152x152.png
 create mode 100644 img/apple-touch-icon-180x180.png
 create mode 100644 img/apple-touch-icon-60x60.png
 create mode 100644 img/apple-touch-icon-76x76.png
 create mode 100644 img/apple-touch-icon.png
 create mode 100644 img/brand-icons.b0ccb869.svg
 create mode 100644 img/favicon-16x16.png
 create mode 100644 img/favicon-32x32.png
 create mode 100644 img/favicon.ico
 create mode 100644 img/flags.6989ab0a.png
 create mode 100644 img/handshake1.c81ff127.webp
 create mode 100644 img/icons-ver1/android-chrome-192x192.png
 create mode 100644 img/icons-ver1/android-chrome-512x512.png
 create mode 100644 img/icons-ver1/android-chrome-maskable-192x192.png
 create mode 100644 img/icons-ver1/android-chrome-maskable-512x512.png
 create mode 100644 img/icons-ver1/apple-touch-icon-120x120.png
 create mode 100644 img/icons-ver1/apple-touch-icon-152x152.png
 create mode 100644 img/icons-ver1/apple-touch-icon-180x180.png
 create mode 100644 img/icons-ver1/apple-touch-icon-60x60.png
 create mode 100644 img/icons-ver1/apple-touch-icon-76x76.png
 create mode 100644 img/icons-ver1/apple-touch-icon.png
 create mode 100644 img/icons-ver1/favicon-16x16.png
 create mode 100644 img/icons-ver1/favicon-32x32.png
 create mode 100644 img/icons-ver1/favicon.ico
 create mode 100644 img/icons-ver1/msapplication-icon-144x144.png
 create mode 100644 img/icons-ver1/mstile-150x150.png
 create mode 100644 img/icons-ver1/safari-pinned-tab.svg
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/android-chrome-192x192.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/android-chrome-512x512.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/android-chrome-maskable-192x192.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/android-chrome-maskable-512x512.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/apple-touch-icon-120x120.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/apple-touch-icon-152x152.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/apple-touch-icon-180x180.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/apple-touch-icon-60x60.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/apple-touch-icon-76x76.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/apple-touch-icon.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/favicon-16x16.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/favicon-32x32.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/favicon.ico"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/msapplication-icon-144x144.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/mstile-150x150.png"
 create mode 100644 "img/icons-\345\216\237\344\276\206\345\234\250img:\344\270\213/safari-pinned-tab.svg"
 create mode 100644 img/icons.a93cf03c.svg
 create mode 100644 img/icons/android-chrome-192x192.png
 create mode 100644 img/icons/android-chrome-512x512.png
 create mode 100644 img/icons/android-chrome-maskable-192x192.png
 create mode 100644 img/icons/android-chrome-maskable-512x512.png
 create mode 100644 img/icons/apple-touch-icon-120x120.png
 create mode 100644 img/icons/apple-touch-icon-152x152.png
 create mode 100644 img/icons/apple-touch-icon-180x180.png
 create mode 100644 img/icons/apple-touch-icon-60x60.png
 create mode 100644 img/icons/apple-touch-icon-76x76.png
 create mode 100644 img/icons/apple-touch-icon.png
 create mode 100644 img/icons/favicon-16x16.png
 create mode 100644 img/icons/favicon-32x32.png
 create mode 100644 img/icons/favicon.ico
 create mode 100644 img/icons/logo-new.png
 create mode 100644 img/icons/msapplication-icon-144x144.png
 create mode 100644 img/icons/mstile-150x150.png
 create mode 100644 img/logo-new.png
 create mode 100644 img/manifest.json
 create mode 100644 img/map1.1c12248b.webp
 create mode 100644 img/msapplication-icon-144x144.png
 create mode 100644 img/mstile-150x150.png
 create mode 100644 img/outline-icons.7af2e9ac.svg
 create mode 100644 img/safari-pinned-tab.svg
 create mode 100644 index.html
 create mode 100644 js/886.54748357.js
 create mode 100644 js/886.54748357.js.map
 create mode 100644 js/about.85cad187.js
 create mode 100644 js/about.85cad187.js.map
 create mode 100644 js/app.abbabb22.js
 create mode 100644 js/app.abbabb22.js.map
 create mode 100644 js/book.6ef90e1f.js
 create mode 100644 js/book.6ef90e1f.js.map
 create mode 100644 js/chunk-vendors.081b6c90.js
 create mode 100644 js/chunk-vendors.081b6c90.js.map
 create mode 100644 js/flag.ec454913.js
 create mode 100644 js/flag.ec454913.js.map
 create mode 100644 js/groups.033810f8.js
 create mode 100644 js/groups.033810f8.js.map
 create mode 100644 js/maps.09bfd3ba.js
 create mode 100644 js/maps.09bfd3ba.js.map
 create mode 100644 js/privacy-policy.5dc0b6de.js
 create mode 100644 js/privacy-policy.5dc0b6de.js.map
 create mode 100644 js/profile.521b4f0e.js
 create mode 100644 js/profile.521b4f0e.js.map
 create mode 100644 js/qr.9744bb99.js
 create mode 100644 js/qr.9744bb99.js.map
 create mode 100644 logo-new-1.png
 create mode 100644 logo-new.png
 create mode 100644 manifest.json
 create mode 100644 robots.txt
 create mode 100644 service-worker.js
 create mode 100644 service-worker.js.map
 create mode 100644 workbox-6567b62a.js
 create mode 100644 workbox-6567b62a.js.map
error: src refspec master does not match any
**error: failed to push some refs to 'github.com:3dw/auto20-next.git'**
(base) chiuhuilee@ChiudeMacBook-Pro 3dw-auto20-next-20240621 % 


**_run sh deploy.sh 錯誤訊息如上，後來我是用手動方式 直接 從我本機 push 到3dw/Autu20-next的gh-pages 分支branch上_**

**Comment by leechiuhui** [comment]
**### Found as below:**
**if Run :**
1. yarn build
2. sh deploy.sh 
**無法更新 3dw/Auto20-Next 的 gh-pages 分支
無法deploy we.alearn.gov.tw 成功**

**but if Run :** 

1. yarn build 
2. yarn add gh-pages --dev 
3. yarn deploy
**可以更新 3dw/Auto20-Next 的 gh-pages 分支
可以deploy we.alearn.gov.tw 成功**
### 
**In fact, I don't know why, teacher.**

**Comment by bestian** [comment]
我也不知道. 這條路我沒走過.
我都是直接設定deploy.sh再直接跑deploy.sh

yarn add gh-pages --dev

是一個安裝gh-pages套件的命令
但gh-pages這個套件似乎不是必要的?

https://www.npmjs.com/package/gh-pages

**Comment by leechiuhui** [comment]
Summary:

1. Running  **yarn build**  followed by  **yarn deploy**  will automatically deploy to the gh-pages branch, as it is configured in the [GitHub Pages settings page](https://github.com/3dw/auto20-next/settings/pages). This will update https://we.alearn.org.tw/.
3. Directly pushing the rebuilt code to https://github.com/3dw/auto20-next will update https://auto20-next.pages.dev/#/.

**Pull request merged**
